### ISSUE TITLE
Kompatibilität Contao 4

### ISSUE THREAD

**Issue by Jaaaan** [Contao3-Ninja/backend_user_online#10]
Im neuen Contao Manager wird die Erweiterung bereits im Katalog angzeigt, jedoch schlägt eine Installation aufgrund fehlender Freigabe für Contao 4 immer fehl. 
Wäre es möglich, diese Freigabe für Contao 4 zu erteilen?  

Infos zu den nötigen Anpassungen: https://github.com/contao-community-alliance/composer-plugin/blob/master/README.md

**Comment by BugBuster1701** [comment]
Nein, aber es wird eine Nachfolger Erweiterung geben wie bei einigen meinen anderen Erweiterungen Stück für Stück auch.

**Comment by BugBuster1701** [comment]
Version 0.1.0 zum Test der Nachfolge Erweiterung veröffentlicht.
"bugbuster/contao-be_user_online-bundle"

**Comment by Jaaaan** [comment]
Danke!
Unter Contao 4 konnten wir bisher keine Komplikationen erkennen.
